import { Octokit } from "@octokit/rest";
import type { Manifest, ProviderId, RegistryEntry } from "./types.ts";

export interface BumpResult {
  repo: string;
  status:
    | "skipped_already_current"
    | "skipped_no_match"
    | "skipped_existing_pr"
    | "opened"
    | "failed";
  url?: string;
  error?: string;
}

function resolveRecommended(
  manifest: Manifest,
  family: string,
): string | undefined {
  const [providerKey, famKey] = family.split(".");
  const provider = manifest.providers[providerKey as ProviderId];
  return provider?.families[famKey]?.recommended;
}

function buildReplacement(template: string, recommended: string): string {
  return template.replace("{recommended}", recommended);
}

export async function bumpEntry(
  octokit: Octokit,
  entry: RegistryEntry,
  manifest: Manifest,
  runUrl: string | undefined,
): Promise<BumpResult> {
  const recommended = resolveRecommended(manifest, entry.family);
  if (!recommended) {
    return {
      repo: entry.repo,
      status: "failed",
      error: `family ${entry.family} not in manifest`,
    };
  }
  const [owner, repo] = entry.repo.split("/");
  const branch = `${entry.branch_prefix}/${entry.family.replace(".", "-")}-${recommended}`;

  // Check for existing open PR for this exact branch.
  const existing = await octokit.pulls.list({
    owner,
    repo,
    head: `${owner}:${branch}`,
    state: "open",
  });
  if (existing.data.length) {
    return {
      repo: entry.repo,
      status: "skipped_existing_pr",
      url: existing.data[0].html_url,
    };
  }

  const repoData = await octokit.repos.get({ owner, repo });
  const baseBranch = repoData.data.default_branch;

  const fileResp = await octokit.repos.getContent({
    owner,
    repo,
    path: entry.file,
    ref: baseBranch,
  });
  if (Array.isArray(fileResp.data) || fileResp.data.type !== "file") {
    return {
      repo: entry.repo,
      status: "failed",
      error: `${entry.file} is not a regular file`,
    };
  }
  const fileSha = fileResp.data.sha;
  const original = Buffer.from(fileResp.data.content, "base64").toString("utf8");

  const re = new RegExp(entry.pattern, "g");
  const replacement = buildReplacement(entry.replacement_template, recommended);
  const updated = original.replace(re, replacement);

  if (!re.test(original)) {
    re.lastIndex = 0;
    if (!new RegExp(entry.pattern).test(original)) {
      return { repo: entry.repo, status: "skipped_no_match" };
    }
  }
  if (updated === original) {
    return { repo: entry.repo, status: "skipped_already_current" };
  }

  const baseRef = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseRef.data.object.sha,
  });

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: entry.file,
    branch,
    sha: fileSha,
    message: `chore: bump ${entry.family} to ${recommended}`,
    content: Buffer.from(updated, "utf8").toString("base64"),
  });

  const body = [
    `Bumps \`${entry.family}\` model to \`${recommended}\`.`,
    "",
    `Generated by [modelmonitor](https://github.com/JMill/modelmonitor).`,
    runUrl ? `Run: ${runUrl}` : "",
  ]
    .filter(Boolean)
    .join("\n");

  const pr = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base: baseBranch,
    title: `chore: bump ${entry.family} to ${recommended}`,
    body,
  });

  if (entry.reviewers.length) {
    await octokit.pulls
      .requestReviewers({
        owner,
        repo,
        pull_number: pr.data.number,
        reviewers: entry.reviewers,
      })
      .catch((err) => {
        console.warn(`requestReviewers failed for ${entry.repo}:`, err);
      });
  }

  return { repo: entry.repo, status: "opened", url: pr.data.html_url };
}
